package squarefootgardenplotgenerator;

import java.util.List;

public class Application {
    public static void main(String[] args) {

        // New objects for getting the user input and the GridMaker.
        GardenerInput userInteraction = new GardenerInput();

        // A new plot is generated by a GridMaker instance within GardenerInput.
        userInteraction.askTheGardener();

    }
}
