package squarefootgardenplotgenerator;

import java.util.List;

public class Application {
    public static void main(String[] args) {

        // New objects for getting the user input and the grid maker.
        GardenerInput userInteraction = new GardenerInput();
        GridMaker makeABetterGarden = new GridMaker();

        // A new list generated by GridMaker.
        List<String> myGrid = makeABetterGarden.makeGrid(userInteraction.askTheGardener(), userInteraction.getRows(), userInteraction.getColumns());

        // This prints the grid since GridMaker only makes the list as an output.
        System.out.println("Here's your garden grid!");
        for (String line : myGrid) {
            System.out.println(line);
        }

    }
}
