package squarefootgardenplotgenerator;

import java.util.*;

public class Application {
    public static void main(String[] args) {

        // New objects for getting the user input and the GridMaker.
        GardenerInput userInteraction = new GardenerInput();

        // A new plot is generated by a GridMaker instance within GardenerInput.
        userInteraction.askTheGardener();

//        int rows = 3;
//        int columns = 2;
//        Map<String, Integer> plantMap = new HashMap<>();
//        plantMap.put("A", 2);
//        plantMap.put("B", 1);
//        plantMap.put("C", 3);
//        plantMap.put("D", 2);
//        plantMap.put("E", 1);
//        plantMap.put("F", 3);
//
//        Queue<String> plantQueue = new LinkedList<>();
//
//        int plantQuantity = 0;
//        do {
//            for (String plant : plantMap.keySet()) {
//                if (plantMap.get(plant) > 0) {
//                    plantQueue.add(plant);
//                    plantMap.put(plant, plantMap.get(plant) - 1);
//                }
//            }
//            plantQuantity = 0;
//            for (String plant : plantMap.keySet()) {
//                plantQuantity += plantMap.get(plant);
//            }
//        } while (plantQuantity > 0);
//
//
//        for (String plant : plantQueue) {
//            System.out.println(plant);
//        }
    }
}
